name: fnbr
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf4f7'
    - '#bad7e7'
    - '#9e938d'
    - '#816d62'
    - '#241d17'
  brandStrength: 0.625
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
