name: fnbr
favicon: null
layout_spectrum: 0.7246282594278455
typography_spectrum: 0.04369387309998274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8563790759071708
  lightness: 0.34541704901494086
  saturation: 0.03574165888130665
  rhythmicContrast: 0.41662604408338666
purpose: []
